name: Solar System Workflow

on:
  workflow_dispatch:
  push:
     branches:
        - main
        - feat/*

jobs:
  unit-testing:
      name: Unit Testing
      runs-on: ubuntu-latest

      steps: 
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Set up Node Js
          uses: actions/setup-node@v3
          with: 
            node-version: 18

        - name: Install Dependencies
          run: npm install

        - name: Run Unit test
          run: npm test
